version: '3'
services:
    bun-discord-bot:
        build:
            context: .
        environment:
            - NODE_ENV=development
            - PORT=3000
            - DEBUG=1
            # - DISCORD_TOKEN=
            # - DISCORD_APP_ID=
            # - OPENROUTER_KEY=
            # - LEONARDO_KEY=
