FROM oven/bun

# Install packages for development
RUN apt-get update && apt-get install -y git curl

# Set working directory
WORKDIR /usr/app

# Copy package.json and package-lock.json before other files
COPY package*.json ./

RUN bun install